# Image Actions will run in the following scenarios:
# - on Pull Requests containing images (not including forks)
# - on pushing of images to `main` (for forks)
# - on demand (https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)
# - at 00:00 every Sunday in anything gets missed with any of the above scenarios
# For Pull Requests, the images are added to the PR.
# For other scenarios, compressed images are committed directly to `main`.

---
name: Compress images

on:
  workflow_dispatch:
  schedule:
    # Every day at 01:00 (UTC)
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    # Only run on main repo
    if: github.repository == 'jasimancas/kometa'
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # Scheduled/manual runs are not PRs, so compressOnly should be true
          compressOnly: true

      - name: Commit and Push to main
        run: |
          # Commit only if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "🍱 Compress Images"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
